#!/usr/bin/python3
import bs4
import sys
import requests


def main(url):
    try:
        with requests.get(url) as res:
            bs4_obj = bs4.BeautifulSoup(res.text, 'html.parser')
            title = bs4_obj.title.string
            print(title)
    except requests.HTTPError as e:
        print(e)


if __name__ == "__main__":
    args = sys.argv
    if len(args) != 2:
        print('Usage: urllink <URL>')
        exit()
    else:
        main(args[1])
